name: Deploy to PyPI

on:
  release:
    types: [created]

jobs:
  Deploying:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Get full python version
        id: full-python-version
        shell: bash
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Install and configure Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Build and publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.pypi_push_token }}
          poetry publish --build
