name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'statnett'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13
      - name: build package
        run: uv build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: 'true'
          attestations: 'false'
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.12
        with:
          verbose: 'true'
          attestations: 'false'
